project_id = "jirisewa"

[db]
port = 54322
major_version = 17

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"

[studio]
enabled = true
port = 54323

[api]
enabled = true
port = 54321
schemas = ["public"]

[auth]
enabled = true
site_url = "http://localhost:3000"

[auth.sms]
enable_signup = true
enable_confirmations = false
template = "Your code is {{ .Code }}"
max_frequency = "0s"

[auth.sms.test_otp]
9779800000001 = "123456"
9779800000002 = "123456"
9779800000003 = "123456"
9779800000004 = "123456"

[storage]
enabled = true

[realtime]
enabled = true
